export const AUTH_INVALID_CREDENTIALS_MAX_ATTEMPTS = 5;
export const AUTH_INVALID_CREDENTIALS_WINDOW_SECONDS = 30;

export const AUTH_INVALID_EMAIL_MAX_ATTEMPTS = 5;
export const AUTH_INVALID_EMAIL_WINDOW_SECONDS = 30;

export const AUTH_OTP_MAX_ATTEMPTS = 10;
export const AUTH_OTP_LOCKOUT_SECONDS = 45;
export const AUTH_OTP_RESEND_COOLDOWN_SECONDS = 60;
