"""phase 3 artifact table

Revision ID: phase3_artifact
Revises: phase3_baseline
Create Date: 2026-07-22 20:24:40.004347+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "phase3_artifact"
down_revision: str | None = "phase3_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_assistant_artifact",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.Text(), server_default=sa.text("'pdf'"), nullable=False),
        sa.Column("report_type", sa.Text(), nullable=True),
        sa.Column("idempotency_hash", sa.Text(), nullable=False),
        sa.Column("request_fingerprint", sa.Text(), nullable=False),
        sa.Column("dataset_checksum", sa.Text(), nullable=True),
        sa.Column("metric_version", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("owner_token", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("relative_path", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column(
            "mime_type", sa.Text(), server_default=sa.text("'application/pdf'"), nullable=True
        ),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("file_sha256", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attached_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind in ('pdf')",
            name=op.f("ck_ai_assistant_artifact_ai_assistant_artifact_kind_check"),
        ),
        sa.CheckConstraint(
            "mime_type is null or mime_type = 'application/pdf'",
            name=op.f("ck_ai_assistant_artifact_ai_assistant_artifact_mime_type_check"),
        ),
        sa.CheckConstraint(
            "status <> 'ready' or (dataset_checksum is not null and file_sha256 is not null)",
            name=op.f("ck_ai_assistant_artifact_ai_assistant_artifact_ready_checksum_check"),
        ),
        sa.CheckConstraint(
            "status in ('pending', 'ready', 'failed')",
            name=op.f("ck_ai_assistant_artifact_ai_assistant_artifact_status_check"),
        ),
        sa.CheckConstraint(
            "byte_size is null or byte_size >= 0",
            name=op.f("ck_ai_assistant_artifact_ai_assistant_artifact_byte_size_check"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["ai_assistant_message.id"],
            name="ai_assistant_artifact_message_id_ai_assistant_message_id_fk",
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["ai_assistant_thread.id"],
            name="ai_assistant_artifact_thread_id_ai_assistant_thread_id_fk",
            ondelete="set null",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_assistant_artifact")),
        sa.UniqueConstraint(
            "idempotency_hash", name="ai_assistant_artifact_idempotency_hash_unique"
        ),
    )
    op.create_index(
        "idx_ai_assistant_artifact_attached_at",
        "ai_assistant_artifact",
        ["attached_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_ai_assistant_artifact_lease_expires_at",
        "ai_assistant_artifact",
        ["lease_expires_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_ai_assistant_artifact_message_id",
        "ai_assistant_artifact",
        ["message_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_ai_assistant_artifact_status",
        "ai_assistant_artifact",
        ["status"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_ai_assistant_artifact_thread_id",
        "ai_assistant_artifact",
        ["thread_id"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_ai_assistant_artifact_thread_id",
        table_name="ai_assistant_artifact",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_ai_assistant_artifact_status",
        table_name="ai_assistant_artifact",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_ai_assistant_artifact_message_id",
        table_name="ai_assistant_artifact",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_ai_assistant_artifact_lease_expires_at",
        table_name="ai_assistant_artifact",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_ai_assistant_artifact_attached_at",
        table_name="ai_assistant_artifact",
        postgresql_using="btree",
    )
    op.drop_table("ai_assistant_artifact")
    # ### end Alembic commands ###
