"""phase 3 baseline

Revision ID: phase3_baseline
Revises:
Create Date: 2026-07-22 20:00:37.514086+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from silo.db.models import Vector768

revision: str = "phase3_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "contact",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("team", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
        sa.UniqueConstraint("email", name="contact_email_unique"),
    )
    op.create_table(
        "group",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "icon", sa.Text(), server_default=sa.text("'icon-[lucide--users]'"), nullable=False
        ),
        sa.Column("color", sa.Text(), server_default=sa.text("'#3B82F6'"), nullable=False),
        sa.Column("role", sa.Text(), server_default=sa.text("'user'"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group")),
        sa.UniqueConstraint("name", name="group_name_unique"),
    )
    op.create_table(
        "help",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=True),
        sa.Column("embedding", Vector768(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_help")),
    )
    op.create_index(
        "idx_help_embedding",
        "help",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "kafka_processed_messages",
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("handler", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("topic", "message_id", name="unique_kafka_processed_message"),
    )
    op.create_table(
        "picture_page",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("check_mode", sa.Text(), server_default=sa.text("'page'"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("delay", sa.Text(), nullable=True),
        sa.Column("delay_minutes", sa.Integer(), nullable=True),
        sa.Column("delayed_links", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("offline_links", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_picture_page")),
        sa.UniqueConstraint("slug", name="picture_page_slug_unique"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("available", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("priority", sa.Text(), server_default=sa.text("'normal'"), nullable=False),
        sa.Column(
            "turns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'["0","6","12","18"]\'::jsonb'),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url_product_flow", sa.Text(), nullable=True),
        sa.Column(
            "data_product_flow",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
    )
    op.create_table(
        "product_problem_category",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_problem_category")),
        sa.UniqueConstraint("name", name="product_problem_category_name_unique"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.Text(), server_default=sa.text("'medium'"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_table(
        "radar_group",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_radar_group")),
        sa.UniqueConstraint("slug", name="radar_group_slug_unique"),
    )
    op.create_table(
        "rate_limit",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("route", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("ip", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("last_request", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit")),
        sa.UniqueConstraint("email", "ip", "route", name="unique_rate_limit_email_ip_route"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name="user_email_unique"),
    )
    op.create_table(
        "verification",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("identifier", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification")),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("id_token", sa.Text(), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="account_user_id_user_id_fk"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
    )
    op.create_table(
        "ai_assistant_thread",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("last_message_preview", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("message_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "last_message_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="ai_assistant_thread_user_id_user_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_assistant_thread")),
    )
    op.create_index(
        "idx_ai_assistant_thread_last_message_at",
        "ai_assistant_thread",
        ["last_message_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_ai_assistant_thread_user_id",
        "ai_assistant_thread",
        ["user_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sender_user_id", sa.Text(), nullable=False),
        sa.Column("receiver_group_id", sa.Text(), nullable=True),
        sa.Column("receiver_user_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receiver_group_id"],
            ["group.id"],
            name="chat_message_receiver_group_id_group_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["receiver_user_id"],
            ["user.id"],
            name="chat_message_receiver_user_id_user_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["user.id"],
            name="chat_message_sender_user_id_user_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_message")),
    )
    op.create_index(
        "idx_chat_message_group",
        "chat_message",
        ["receiver_group_id", "created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_chat_message_sender",
        "chat_message",
        ["sender_user_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_chat_message_unread_user",
        "chat_message",
        ["receiver_user_id", "read_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_chat_message_user",
        "chat_message",
        ["receiver_user_id", "sender_user_id", "created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "chat_user_presence",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'invisible'"), nullable=False),
        sa.Column("last_activity", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="chat_user_presence_user_id_user_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_chat_user_presence")),
    )
    op.create_table(
        "group_permissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("group_id", sa.Text(), nullable=False),
        sa.Column("resource", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
            name="group_permissions_group_id_group_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_permissions")),
        sa.UniqueConstraint("group_id", "resource", "action", name="unique_group_permission"),
    )
    op.create_index(
        "idx_group_permission_group_id",
        "group_permissions",
        ["group_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_group_permission_resource",
        "group_permissions",
        ["resource"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "picture_link",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("page_id", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("size", sa.Text(), nullable=True),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.Column("delay", sa.Text(), nullable=True),
        sa.Column("delay_minutes", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["picture_page.id"],
            name="picture_link_page_id_picture_page_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_picture_link")),
        sa.UniqueConstraint("slug", name="picture_link_slug_unique"),
    )
    op.create_table(
        "product_activity",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("turn", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("problem_category_id", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("intervention", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_category_id"],
            ["product_problem_category.id"],
            name="product_activity_problem_category_id_product_problem_category_i",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name="product_activity_product_id_product_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="product_activity_user_id_user_id_fk", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_activity")),
        sa.UniqueConstraint(
            "product_id", "date", "turn", name="unique_product_activity_product_date_turn"
        ),
    )
    op.create_index(
        "idx_product_activity_product_date",
        "product_activity",
        ["product_id", "date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_product_activity_product_turn",
        "product_activity",
        ["product_id", "turn"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_product_activity_user_id",
        "product_activity",
        ["user_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "product_availability_exception",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name="product_availability_exception_product_id_product_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_availability_exception")),
        sa.UniqueConstraint(
            "product_id",
            "date",
            "type",
            name="unique_product_availability_exception_product_date_type",
        ),
    )
    op.create_index(
        "idx_product_availability_exception_product_date",
        "product_availability_exception",
        ["product_id", "date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "product_contact",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("contact_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name="product_contact_contact_id_contact_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name="product_contact_product_id_product_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_contact")),
    )
    op.create_table(
        "product_dependency",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Text(), nullable=True),
        sa.Column("tree_path", sa.Text(), nullable=True),
        sa.Column("tree_depth", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sort_key", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name="product_dependency_product_id_product_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_dependency")),
    )
    op.create_table(
        "product_manual",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name="product_manual_product_id_product_id_fk"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_manual")),
    )
    op.create_table(
        "product_problem",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("problem_category_id", sa.Text(), nullable=True),
        sa.Column("embedding", Vector768(), nullable=True),
        sa.ForeignKeyConstraint(
            ["problem_category_id"],
            ["product_problem_category.id"],
            name="product_problem_problem_category_id_product_problem_category_id",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name="product_problem_product_id_product_id_fk"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="product_problem_user_id_user_id_fk"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_problem")),
    )
    op.create_index(
        "idx_product_problem_category",
        "product_problem",
        ["problem_category_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_product_problem_created_at",
        "product_problem",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_product_problem_description_trgm",
        "product_problem",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_product_problem_embedding",
        "product_problem",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "idx_product_problem_product",
        "product_problem",
        ["product_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_product_problem_title_trgm",
        "product_problem",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_product_problem_user",
        "product_problem",
        ["user_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "project_activity",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("estimated_days", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.Text(), server_default=sa.text("'medium'"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'todo'"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="project_activity_project_id_project_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_activity")),
    )
    op.create_table(
        "radar",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("group_id", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("webhook_url", sa.Text(), nullable=True),
        sa.Column("log_url", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("delay", sa.Text(), nullable=True),
        sa.Column("delay_minutes", sa.Integer(), nullable=True),
        sa.Column("log_date", sa.DateTime(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["radar_group.id"],
            name="radar_group_id_radar_group_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_radar")),
        sa.UniqueConstraint("slug", name="radar_slug_unique"),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="session_user_id_user_id_fk"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
        sa.UniqueConstraint("token", name="session_token_unique"),
    )
    op.create_table(
        "user_group",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("group_id", sa.Text(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["group.id"], name="user_group_group_id_group_id_fk", ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_group_user_id_user_id_fk", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_group")),
        sa.UniqueConstraint("user_id", "group_id", name="unique_user_group"),
    )
    op.create_index(
        "idx_user_group_group_id",
        "user_group",
        ["group_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_user_group_user_id", "user_group", ["user_id"], unique=False, postgresql_using="btree"
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("chat_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_preferences_user_id_user_id_fk"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("genre", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("team", sa.Text(), nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="user_profile_user_id_user_id_fk"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profile")),
    )
    op.create_table(
        "ai_assistant_message",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("sender_type", sa.Text(), server_default=sa.text("'user'"), nullable=False),
        sa.Column("sender_user_id", sa.Text(), nullable=True),
        sa.Column("sender_name", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("generation_status", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("embedding", Vector768(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["user.id"],
            name="ai_assistant_message_sender_user_id_user_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["ai_assistant_thread.id"],
            name="ai_assistant_message_thread_id_ai_assistant_thread_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_assistant_message")),
    )
    op.create_index(
        "idx_ai_assistant_message_created_at",
        "ai_assistant_message",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_ai_assistant_message_thread_id",
        "ai_assistant_message",
        ["thread_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_ai_message_embedding",
        "ai_assistant_message",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "product_activity_history",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_activity_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("intervention", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_activity_id"],
            ["product_activity.id"],
            name="product_activity_history_product_activity_id_product_activity_i",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="product_activity_history_user_id_user_id_fk"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_activity_history")),
    )
    op.create_index(
        "idx_product_activity_history_created_at",
        "product_activity_history",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_product_activity_history_product_activity_id",
        "product_activity_history",
        ["product_activity_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_product_activity_history_user_id",
        "product_activity_history",
        ["user_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "product_manual_chunk",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("product_manual_id", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("embedding", Vector768(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name="product_manual_chunk_product_id_product_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["product_manual_id"],
            ["product_manual.id"],
            name="product_manual_chunk_product_manual_id_product_manual_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_manual_chunk")),
    )
    op.create_index(
        "idx_product_manual_chunk_content_trgm",
        "product_manual_chunk",
        ["content"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_product_manual_chunk_embedding",
        "product_manual_chunk",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "idx_product_manual_chunk_product_id",
        "product_manual_chunk",
        ["product_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "product_problem_image",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("product_problem_id", sa.Text(), nullable=False),
        sa.Column("image", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_problem_id"],
            ["product_problem.id"],
            name="product_problem_image_product_problem_id_product_problem_id_fk",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_problem_image")),
    )
    op.create_table(
        "product_solution",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("product_problem_id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reply_id", sa.Text(), nullable=True),
        sa.Column("embedding", Vector768(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_problem_id"],
            ["product_problem.id"],
            name="product_solution_product_problem_id_product_problem_id_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="product_solution_user_id_user_id_fk"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_solution")),
    )
    op.create_index(
        "idx_product_solution_description_trgm",
        "product_solution",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_product_solution_embedding",
        "product_solution",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "project_task",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("project_activity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("estimated_days", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.Text(), server_default=sa.text("'medium'"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'todo'"), nullable=False),
        sa.Column("sort", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_activity_id"],
            ["project_activity.id"],
            name="project_task_project_activity_id_project_activity_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="project_task_project_id_project_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_task")),
    )
    op.create_table(
        "product_solution_checked",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("product_solution_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_solution_id"],
            ["product_solution.id"],
            name="product_solution_checked_product_solution_id_product_solution_i",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="product_solution_checked_user_id_user_id_fk"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_solution_checked")),
    )
    op.create_table(
        "product_solution_image",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("product_solution_id", sa.Text(), nullable=False),
        sa.Column("image", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_solution_id"],
            ["product_solution.id"],
            name="product_solution_image_product_solution_id_product_solution_id_",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_solution_image")),
    )
    op.create_table(
        "project_task_history",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("from_status", sa.Text(), nullable=True),
        sa.Column("to_status", sa.Text(), nullable=False),
        sa.Column("from_sort", sa.Integer(), nullable=True),
        sa.Column("to_sort", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["project_task.id"],
            name="project_task_history_task_id_project_task_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="project_task_history_user_id_user_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_task_history")),
    )
    op.create_index(
        "idx_project_task_history_created_at",
        "project_task_history",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_project_task_history_task_id",
        "project_task_history",
        ["task_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_project_task_history_user_id",
        "project_task_history",
        ["user_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "project_task_user",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default=sa.text("'assignee'"), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["project_task.id"],
            name="project_task_user_task_id_project_task_id_fk",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="project_task_user_user_id_user_id_fk",
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_task_user")),
        sa.UniqueConstraint("task_id", "user_id", name="unique_task_user"),
    )
    op.create_index(
        "idx_project_task_user_task_id",
        "project_task_user",
        ["task_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_project_task_user_user_id",
        "project_task_user",
        ["user_id"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_project_task_user_user_id", table_name="project_task_user", postgresql_using="btree"
    )
    op.drop_index(
        "idx_project_task_user_task_id", table_name="project_task_user", postgresql_using="btree"
    )
    op.drop_table("project_task_user")
    op.drop_index(
        "idx_project_task_history_user_id",
        table_name="project_task_history",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_project_task_history_task_id",
        table_name="project_task_history",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_project_task_history_created_at",
        table_name="project_task_history",
        postgresql_using="btree",
    )
    op.drop_table("project_task_history")
    op.drop_table("product_solution_image")
    op.drop_table("product_solution_checked")
    op.drop_table("project_task")
    op.drop_index(
        "idx_product_solution_embedding",
        table_name="product_solution",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "idx_product_solution_description_trgm",
        table_name="product_solution",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.drop_table("product_solution")
    op.drop_table("product_problem_image")
    op.drop_index(
        "idx_product_manual_chunk_product_id",
        table_name="product_manual_chunk",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_product_manual_chunk_embedding",
        table_name="product_manual_chunk",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "idx_product_manual_chunk_content_trgm",
        table_name="product_manual_chunk",
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.drop_table("product_manual_chunk")
    op.drop_index(
        "idx_product_activity_history_user_id",
        table_name="product_activity_history",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_product_activity_history_product_activity_id",
        table_name="product_activity_history",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_product_activity_history_created_at",
        table_name="product_activity_history",
        postgresql_using="btree",
    )
    op.drop_table("product_activity_history")
    op.drop_index(
        "idx_ai_message_embedding",
        table_name="ai_assistant_message",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "idx_ai_assistant_message_thread_id",
        table_name="ai_assistant_message",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_ai_assistant_message_created_at",
        table_name="ai_assistant_message",
        postgresql_using="btree",
    )
    op.drop_table("ai_assistant_message")
    op.drop_table("user_profile")
    op.drop_table("user_preferences")
    op.drop_index("idx_user_group_user_id", table_name="user_group", postgresql_using="btree")
    op.drop_index("idx_user_group_group_id", table_name="user_group", postgresql_using="btree")
    op.drop_table("user_group")
    op.drop_table("session")
    op.drop_table("radar")
    op.drop_table("project_activity")
    op.drop_index(
        "idx_product_problem_user", table_name="product_problem", postgresql_using="btree"
    )
    op.drop_index(
        "idx_product_problem_title_trgm",
        table_name="product_problem",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_product_problem_product", table_name="product_problem", postgresql_using="btree"
    )
    op.drop_index(
        "idx_product_problem_embedding",
        table_name="product_problem",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "idx_product_problem_description_trgm",
        table_name="product_problem",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_product_problem_created_at", table_name="product_problem", postgresql_using="btree"
    )
    op.drop_index(
        "idx_product_problem_category", table_name="product_problem", postgresql_using="btree"
    )
    op.drop_table("product_problem")
    op.drop_table("product_manual")
    op.drop_table("product_dependency")
    op.drop_table("product_contact")
    op.drop_index(
        "idx_product_availability_exception_product_date",
        table_name="product_availability_exception",
        postgresql_using="btree",
    )
    op.drop_table("product_availability_exception")
    op.drop_index(
        "idx_product_activity_user_id", table_name="product_activity", postgresql_using="btree"
    )
    op.drop_index(
        "idx_product_activity_product_turn", table_name="product_activity", postgresql_using="btree"
    )
    op.drop_index(
        "idx_product_activity_product_date", table_name="product_activity", postgresql_using="btree"
    )
    op.drop_table("product_activity")
    op.drop_table("picture_link")
    op.drop_index(
        "idx_group_permission_resource", table_name="group_permissions", postgresql_using="btree"
    )
    op.drop_index(
        "idx_group_permission_group_id", table_name="group_permissions", postgresql_using="btree"
    )
    op.drop_table("group_permissions")
    op.drop_table("chat_user_presence")
    op.drop_index("idx_chat_message_user", table_name="chat_message", postgresql_using="btree")
    op.drop_index(
        "idx_chat_message_unread_user", table_name="chat_message", postgresql_using="btree"
    )
    op.drop_index("idx_chat_message_sender", table_name="chat_message", postgresql_using="btree")
    op.drop_index("idx_chat_message_group", table_name="chat_message", postgresql_using="btree")
    op.drop_table("chat_message")
    op.drop_index(
        "idx_ai_assistant_thread_user_id",
        table_name="ai_assistant_thread",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_ai_assistant_thread_last_message_at",
        table_name="ai_assistant_thread",
        postgresql_using="btree",
    )
    op.drop_table("ai_assistant_thread")
    op.drop_table("account")
    op.drop_table("verification")
    op.drop_table("user")
    op.drop_table("rate_limit")
    op.drop_table("radar_group")
    op.drop_table("project")
    op.drop_table("product_problem_category")
    op.drop_table("product")
    op.drop_table("picture_page")
    op.drop_table("kafka_processed_messages")
    op.drop_index(
        "idx_help_embedding",
        table_name="help",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("help")
    op.drop_table("group")
    op.drop_table("contact")
    # ### end Alembic commands ###
