export const AUTH_INVALID_CREDENTIALS_MAX_ATTEMPTS = 5;
export const AUTH_INVALID_CREDENTIALS_WINDOW_SECONDS = 30;

export const AUTH_INVALID_EMAIL_MAX_ATTEMPTS = 5;
export const AUTH_INVALID_EMAIL_WINDOW_SECONDS = 30;

export const AUTH_OTP_MAX_ATTEMPTS = 10;
export const AUTH_OTP_LOCKOUT_SECONDS = 45;
export const AUTH_OTP_RESEND_COOLDOWN_SECONDS = 60;

export const AUTH_SESSION_DURATION_DAYS = 365;
export const AUTH_SESSION_DURATION_SECONDS =
  AUTH_SESSION_DURATION_DAYS * 24 * 60 * 60;
export const AUTH_SESSION_UPDATE_AGE_SECONDS = 24 * 60 * 60;
