from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from silo.api.main import create_app

REPOSITORY_ROOT = Path(__file__).resolve().parents[5]
DEFAULT_JSON_OUTPUT = (
    REPOSITORY_ROOT / "packages" / "engine" / "src" / "contracts" / "generated" / "openapi.json"
)
DEFAULT_TS_OUTPUT = (
    REPOSITORY_ROOT / "packages" / "engine" / "src" / "contracts" / "generated" / "openapi.ts"
)


def generate_openapi_document() -> dict[str, Any]:
    return create_app().openapi()


def render_openapi_json(document: dict[str, Any]) -> str:
    import json

    return json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_openapi_typescript(document: dict[str, Any]) -> str:
    return "\n".join(
        (
            "/* eslint-disable */",
            "// Auto-generated by `npm run py:openapi`. Do not edit manually.",
            "",
            f"export const siloPythonOpenApi = {render_openapi_json(document).rstrip()} as const;",
            "",
            "export type SiloPythonOpenApi = typeof siloPythonOpenApi;",
            "",
        )
    )


def write_or_check(path: Path, content: str, *, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Export SILO Python API OpenAPI contract.")
    parser.add_argument("--json-output", type=Path, default=DEFAULT_JSON_OUTPUT)
    parser.add_argument("--ts-output", type=Path, default=DEFAULT_TS_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    document = generate_openapi_document()
    outputs = {
        args.json_output: render_openapi_json(document),
        args.ts_output: render_openapi_typescript(document),
    }

    outdated_paths: list[Path] = []
    for path, content in outputs.items():
        if not write_or_check(path, content, check=args.check):
            outdated_paths.append(path)

    if outdated_paths:
        for path in outdated_paths:
            print(f"OpenAPI generated artifact is outdated: {path}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
